//
//  VersusMessage.swift
//  Tertia
//
//  Wire-level message protocol for versus matches. Both peers serialize
//  values of this enum to JSON and exchange them over the GKMatch transport.
//
//  Versioning note: if a future Tertia release changes the schema (adds a
//  case, renames a field), set a `protocolVersion` field at the envelope
//  level so peers can detect mismatches and surface a friendly "your friend
//  needs to update" message rather than silently dropping malformed data.
//  For v1 we ship without that envelope — keep this in mind before
//  changing message shapes after launch.
//

import Foundation

/// Game Center player identifier — `GKPlayer.gamePlayerID`. A stable string
/// per Apple ID. Aliased so call sites read clearly.
typealias VersusPlayerID = String

/// Wire-friendly card descriptor. SetCard's UUID is generated fresh on each
/// peer's process, so it can't be used to reference cards across the network.
/// The (shape, count, color, fill) tuple uniquely identifies a card in the
/// 81-card deck — there are no duplicates — so peers use this on the wire
/// and resolve back to local SetCard instances by attribute matching.
struct WireCard: Codable, Equatable, Hashable, Sendable {
    let shape: CardShape
    let count: CardCount
    let color: CardColor
    let fill: CardFill
}

extension SetCard {
    var wire: WireCard {
        WireCard(shape: shape, count: count, color: color, fill: fill)
    }
}

extension WireCard {
    /// Finds the local SetCard with these attributes inside `cards`. Returns
    /// nil if the card has already been removed from the board.
    func resolve(in cards: [SetCard]) -> SetCard? {
        cards.first {
            $0.shape == shape && $0.count == count && $0.color == color && $0.fill == fill
        }
    }
}

enum VersusMessage: Codable, Equatable, Sendable {
    /// Sent once by the host at match start so the guest can build the same
    /// deterministic deck via `DailyPuzzle`-style seeded LCG. The seed is
    /// generated fresh per match (not derived from the date).
    case deckSeed(UInt64)

    /// Guest → host: "I'm trying to claim these three cards." Host validates,
    /// applies if first valid claim wins the race, and broadcasts a
    /// `.claimResult` to both peers.
    ///
    /// `claimID` is generated by the claimer and echoed in `claimResult` so
    /// duplicate claims from a flaky network can be deduplicated by the host
    /// and correlated by the claimer when the result arrives.
    case claim(cards: [WireCard], at: Date, claimID: UUID)

    /// Host → both peers (including itself for symmetry): result of a claim
    /// arbitration. `success: false` means the claim lost a race or was
    /// invalid; the loser starts a 1.5s lockout locally on receipt.
    case claimResult(
        winner: VersusPlayerID,
        cards: [WireCard],
        success: Bool,
        hostScore: Int,
        guestScore: Int,
        hostTrios: Int,
        guestTrios: Int,
        claimID: UUID
    )

    /// Either peer → host: "There's no trio on the board, deal three more."
    /// Host validates the request (board really has no trio, deck has cards)
    /// and responds with `.dealThreeAck` if it applied.
    case dealThreeRequest(by: VersusPlayerID)

    /// Host → both peers: confirms that three more cards were dealt. The
    /// authoritative new cards are included so guests can append them to
    /// their local board even if state has drifted.
    case dealThreeAck(newCards: [WireCard])

    /// Either peer → both: pre-game confirmation handshake. Both peers send
    /// this with `accepted: true` to start the match; either sending
    /// `accepted: false` aborts before any deck is seeded. Lets players
    /// double-confirm after GameKit's matchmaker hands them an opponent —
    /// the popup is the "last chance to back out" before the game starts.
    ///
    /// `variant` is the sender's selected versus variant. With GameKit's
    /// `playerGroup` gating, peers should already agree, but echoing it
    /// here lets the StubMatchTransport test path verify and gives a
    /// belt-and-suspenders fallback for misconfigured clients — a peer
    /// receiving a mismatched variant declines the match.
    case matchConfirmation(by: VersusPlayerID, accepted: Bool, variant: VersusVariant)

    /// Either peer → both: this player has forfeited. Recipient ends the
    /// match and records a forfeit in their VersusStore.
    case forfeit(by: VersusPlayerID)

    /// Either peer → both: "I want to rematch." Match transitions into a
    /// fresh game (new deck seed, scores reset) only after both peers have
    /// sent this within the 15s window.
    case rematchRequest(by: VersusPlayerID)

    /// Either peer → both: "I'm done — no rematch." Lets the other peer
    /// short-circuit their 15s wait and surface the "opponent left"
    /// suggestion immediately.
    case rematchDecline(by: VersusPlayerID)

    /// Periodic keep-alive. Receiver updates its watchdog timestamp; absence
    /// of heartbeats for the disconnect-grace window triggers an auto-forfeit.
    case heartbeat(at: Date)
}
